platform :ios, '13.0'

flutter_application_path = 'flutter_host_app'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'test1' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer)
end